export const vietnameseQuotes: string[] = [
    "Học, học nữa, học mãi.",
    "Tri thức là sức mạnh.",
    "Giáo dục là vũ khí mạnh nhất mà bạn có thể sử dụng để thay đổi thế giới.",
    "Tương lai phụ thuộc vào điều chúng ta làm trong hiện tại.",
    "Đừng đợi cơ hội; hãy tạo ra nó.",
    "Cách tốt nhất để dự đoán tương lai là tạo ra nó.",
    "Thất bại duy nhất là không cố gắng.",
    "Hãy là sự thay đổi mà bạn muốn thấy trên thế giới.",
    "Không có gì là không thể với một người luôn biết cố gắng.",
    "Hành trình vạn dặm bắt đầu bằng một bước chân.",
    "Thiên tài là một phần trăm cảm hứng và chín mươi chín phần trăm mồ hôi.",
    "Hãy học từ ngày hôm qua, sống cho ngày hôm nay, hy vọng cho ngày mai.",
    "Logic sẽ đưa anh từ điểm A đến điểm B. Trí tưởng tượng sẽ đưa anh đi khắp mọi nơi.",
    "Người đọc sách có một lợi thế lớn so với người không thể đọc.",
    "Mục đích của giáo dục là thay một cái đầu rỗng bằng một cái đầu rộng mở.",
    "Chỉ có một điều khiến giấc mơ không thể đạt được: đó là nỗi sợ thất bại.",
    "Hãy tin rằng bạn có thể và bạn đã đi được nửa đường.",
    "Thử thách là thứ làm cho cuộc sống trở nên thú vị, và vượt qua chúng là ý nghĩa của cuộc sống.",
    "Hãy nhắm tới mặt trăng. Dù có trượt, bạn cũng sẽ ở giữa những vì sao.",
    "Người duy nhất bạn nên cố gắng để trở nên tốt hơn chính là bạn của ngày hôm qua.",
    "Kiến thức đầu tư mang lại lợi nhuận tốt nhất.",
    "Giáo dục là tấm hộ chiếu đến tương lai, vì ngày mai thuộc về những người chuẩn bị cho nó ngày hôm nay.",
    "Chỉ những người dám thất bại lớn mới có thể đạt được thành công lớn.",
    "Không có con đường tắt đến bất kỳ nơi nào đáng để đến.",
    "Sự khác biệt giữa bình thường và phi thường là một chút 'thêm'.",
    "Thành công không phải là chìa khóa của hạnh phúc. Hạnh phúc là chìa khóa của thành công.",
    "Kỷ luật là cầu nối giữa mục tiêu và thành tựu.",
    "Nếu bạn có thể mơ, bạn có thể làm được.",
    "Bắt đầu từ nơi bạn đứng. Sử dụng những gì bạn có. Làm những gì bạn có thể.",
    "Một nhà lãnh đạo là người biết đường, đi trên con đường đó và chỉ cho người khác con đường đó.",
    "Thời gian của bạn có hạn, đừng lãng phí nó để sống cuộc đời của người khác.",
    "Một người chưa từng mắc lỗi là người chưa từng thử bất cứ điều gì mới.",
    "Không quan trọng bạn đi chậm như thế nào, miễn là bạn không dừng lại.",
    "Sự sáng tạo là trí thông minh đang vui đùa.",
    "Những gì tâm trí con người có thể nhận thức và tin tưởng, nó có thể đạt được.",
    "Để thành công, khát vọng thành công của bạn phải lớn hơn nỗi sợ thất bại.",
    "Đừng để những gì bạn không thể làm cản trở những gì bạn có thể làm.",
    "Chúng ta trở thành những gì chúng ta nghĩ đến.",
    "Chất lượng không phải là một hành động, nó là một thói quen.",
    "Sự trả thù tốt nhất là thành công vang dội."
];
